version: "3"

services:
  jenkins-docker:
    image: docker:dind
    ports:
      - "2376:2376"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    privileged: true
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      ci:
        aliases:
         - docker

  jenkins-blueocean:
    image: jenkinsci/blueocean
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - ci

  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081
    networks:
      - ci

  sonar:
    image: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    networks:
      - ci

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  ci: